# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sq0tBSwPcwGO3dsfS7LBKbtwdMY8AIN9
"""

pip install kaggle

import pandas as pd
from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d nyagami/video-game-ratings-from-imdb

!unzip video-game-ratings-from-imdb.zip && rm video-game-ratings-from-imdb.zip

df = pd.read_csv('/content/imdb_video_game_rating.csv')
!pwd
!mkdir my_project

cd my_project

def state(b):
  x = 5*b+4
  print(x)

state(8)

mv ../imdb_video_game_rating.csv .